### ISSUE TITLE
Setup libretime.org email addresses and aliases

### ISSUE THREAD

**Issue by jooola** [libretime/organization#19]
Once #18 is completed, we can setup some email address for LibreTime.

Such as the security email address or a shared alias for basic administration.

**Comment by jooola** [comment]
Now that we can configure our email aliases, I propose to draft a email routing schema, and configure it.

I am unsure if we should have only aliases, or if we create a shared mailbox. Maybe just one ?

```
org@ mailbox

security@ aliases
  to org@
  to our emails ?
```

What other aliases do we need ?

**Comment by jooola** [comment]
Once this is complete, I'll change the Github libretime-bot account to use the new email addresses.

**Comment by paddatrapper** [comment]
I agree that aliases are probably all we need. Maybe maintainers@, security@ and bots@?

**Comment by jooola** [comment]
Great, this is now solved. I added all the aliases you mentioned.

If you want details about the routing, please go to the admin interface, maybe it's not smart to make all this too public and recognizable by spammers.
