### ISSUE TITLE
Get access to the libretime discourse administration

### ISSUE THREAD

**Issue by jooola** [libretime/organization#23]
We need access to the discourse administration.

@Robbt is currently the admin, but we should probably add some more admins.

I mainly need this to setup a template for users that ask for help, they need to fill more information.

I will start to get angry at those who don't, but in the the end is our fault because we don't provide information about what information to collect, hence the template I want to setup.

**Comment by Robbt** [comment]
I'm happy to give you admin access send me a message on there and I'll add you.

**Comment by Robbt** [comment]
Ok I found your user and made you an admin.

**Comment by jooola** [comment]
Great thanks a lot ! I also added @paddatrapper as admin.
