### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by jooola** [libretime/organization#3]
According to https://github.com/libretime/libretime/issues/1713 this repo had a bigger purpose as only storing a code of conduct.

So to make this idea happen, we should rename this repo to something more generic, like 'org' or 'meta' or something else, I don't have any specific idea.

**Comment by paddatrapper** [comment]
I like organization?

**Comment by jooola** [comment]
Sounds good to me.

**Comment by paddatrapper** [comment]
Renamed. There is a PR up to fix the URLs in libretime
