### ISSUE TITLE
Apply to Dockerhub Open source program

### ISSUE THREAD

**Issue by jooola** [libretime/organization#31]
We received a mail from docker hub warning us that they are sun-setting the free team organizations:

---

Docker is sunsetting Free Team organizations

Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.

After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.

If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization.

If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our [FAQ](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf) for more information.

---

We recently started mirroring our images from ghcr.io to docker.io, and we rely on this free team organizations. The impact is minimal for LibreTime, as we never relied on docker hub for hosting our images, the docker-compose file always referenced the images on ghcr.io.

But since we have some images hosted at docker hub, here is what I propose to get us out of this situation:

- We apply for the docker hub open source program https://www.docker.com/community/open-source/application/. We renew this application every year.
- We prefer ghcr.io as base registry for all our images. We use the docker.io registry only for the discoverability it brings to the project until we find a better alternative and that moving away from there brings some benefits.
- We assume Docker hub might do similar moves in the future: we must not depend on docker hub and be prepared to drop it at any time.

@paddatrapper I need your green light to apply for the open source program on docker hub.

**Comment by paddatrapper** [comment]
Yup, go ahead

**Comment by jooola** [comment]
Application send, they say it may take 30 days or more for them to review our demand :rofl:.

**Comment by paddatrapper** [comment]
Joy... At least the data is retained past 30 days from now!

**Comment by jooola** [comment]
https://web.archive.org/web/20230329173631/https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

Let's join the open source program anyway.

**Comment by jooola** [comment]
We have been approved to the docker open source program.

```
A Docker Team subscription will be allocated to the project organization Docker ID specified in your application within the next 3 weeks.
```

**Comment by jooola** [comment]
Docker is asking us to have a personal docker ID attached to the maintainers email address, so I assume we have a create yet another account with this email ?

We have to give feedback within 3 business days.

@paddatrapper What did you understand from that email ?

**Comment by paddatrapper** [comment]
Yes, I got the same understanding. Shall I create it or will you?

**Comment by jooola** [comment]
Hmm, feel free to create it, if you have some time.

I am a bit confused, as we cannot use the libretime username as it is already taken by our org...

**Comment by paddatrapper** [comment]
I've created libretimemaintainers and the credentials are in the password vault

**Comment by jooola** [comment]
Awesome!

**Comment by jooola** [comment]
Confirmation we just received on our mailbox.
