### ISSUE TITLE
Move the community channels to Matrix

### ISSUE THREAD

**Issue by jooola** [libretime/organization#33]
We are planning on moving the community channels (currently on a Mattermost server, hosted by @paddatrapper) to a Matrix Space.

An alternative would be to continue hosting a Mattermost server, but on our own infrastructure.

- The initial proposal came from @paddatrapper 
- I am in favor of moving to Matrix.

This will need the following steps :
- [x] Set up the matrix space
- [ ] Create a blog post to announce the change. The blog post will also be sent on the current Mattermost and the Forum.
- [ ] Archive the data from Mattermost (channels, not the private message). This data should not be publicly accessible for unknown users or robots, as it was previously hidden behind a registration wall.
- [ ] Shutdown the Mattermost server

I am unsure about the timeline, once agreed, I think the move can be pretty quick. Maybe we need to keep the deprecated Mattermost server one week up after the announcement (tough, I don't see any reason why) ?

Before doing so, we need some more input from the maintainers of the project. @libretime/administrators

**Comment by jooola** [comment]
I'd say we can go ahead and stop waiting for the input of @Robbt or @hairmare.

**Comment by paddatrapper** [comment]
Yeah, I'm happy to start drafting a blog post
