### ISSUE TITLE
Should we enable discussions on this repo ?

### ISSUE THREAD

**Issue by jooola** [libretime/organization#5]
I wonder if we should bother to enable discussions on this repo, as swapping issues and discussions is pretty easy, and would allow to discuss ideas before moving them to real issues.

That would generate an extra forum like for LibreTime, duplicating discourse and I don't know if we have a use for this. I'm not using discourse a lot though, it feels more like we could use a dedicated place to discuss financial/organizational topics without newcomers asking for help (hope this doesn't sound mean towards newcomers).

Or maybe I didn't find any dedicated place were such discussion can happen appart from the (closed source) admin team panel, and the dev topic category on discourse.

**Comment by paddatrapper** [comment]
My thought is probably not. We can create several new categories in discourse for things that aren't funding requests and issues in this repo for the requests. Even if there is some discussion on the request in the issue, that is fine.
